const pdf = require("pdf-parse");
import mammoth from "mammoth";
import officeparser from "officeparser";
import * as XLSX from "xlsx";

// Supported file types configuration
export type SupportedFileType =
  | "pdf"
  | "docx"
  | "pptx"
  | "xlsx"
  | "txt"
  | "md"
  | "png"
  | "jpeg"
  | "jpg";

const MIME_TO_TYPE: Record<string, SupportedFileType> = {
  "application/pdf": "pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
    "docx",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation":
    "pptx",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": "xlsx",
  "application/vnd.ms-excel": "xlsx",
  "text/plain": "txt",
  "text/markdown": "md",
  "image/png": "png",
  "image/jpeg": "jpeg",
  "image/jpg": "jpg",
};

const EXTENSION_TO_TYPE: Record<string, SupportedFileType> = {
  ".pdf": "pdf",
  ".docx": "docx",
  ".pptx": "pptx",
  ".xlsx": "xlsx",
  ".xls": "xlsx",
  ".txt": "txt",
  ".md": "md",
  ".png": "png",
  ".jpeg": "jpeg",
  ".jpg": "jpg",
};

export interface ParsedPage {
  pageNumber: number;
  text: string;
  image?: Buffer;
}

export interface ParsedDocument {
  text: string;
  pages: ParsedPage[];
  /** Marker 結構化 chunks（僅 Marker 解析時存在） */
  markerChunks?: import("./marker-client").MarkerChunk[];
  /** 解析器來源 */
  parsedBy?: "marker" | "builtin";
}

export function detectFileType(
  mimeType: string,
  fileName: string,
): SupportedFileType | null {
  const fromMime = MIME_TO_TYPE[mimeType];
  if (fromMime) return fromMime;
  const ext = fileName.toLowerCase().match(/\.[^.]+$/)?.[0] ?? "";
  return EXTENSION_TO_TYPE[ext] ?? null;
}

export async function parseFile(
  buffer: Buffer,
  fileType: SupportedFileType,
): Promise<ParsedDocument> {
  switch (fileType) {
    case "pdf":
      return parsePdf(buffer);
    case "docx":
      return wrapSinglePage(await parseDocx(buffer));
    case "pptx":
      return wrapSinglePage(await parsePptx(buffer));
    case "xlsx":
      return wrapSinglePage(await parseXlsx(buffer));
    case "txt":
    case "md":
      return wrapSinglePage(buffer.toString("utf-8"));
    case "png":
    case "jpeg":
    case "jpg":
      return {
        text: "", // Text will be generated by vision model
        pages: [{ pageNumber: 1, text: "", image: buffer }],
      };
  }
}

function wrapSinglePage(text: string): ParsedDocument {
  return {
    text,
    pages: [{ pageNumber: 1, text }],
  };
}

/**
 * PDF Parsing using pdf-parse with per-page text extraction.
 *
 * Uses a custom `pagerender` callback to collect each page's text
 * individually, preserving page numbers for downstream chunking.
 */
async function parsePdf(buffer: Buffer): Promise<ParsedDocument> {
  try {
    const collectedPages: ParsedPage[] = [];
    let pageIndex = 0;

    // Custom pagerender callback — called once per page by pdf-parse
    const pagerender = (pageData: {
      getTextContent: (opts: {
        normalizeWhitespace: boolean;
        disableCombineTextItems: boolean;
      }) => Promise<{
        items: Array<{ str: string; transform: number[] }>;
      }>;
    }): Promise<string> => {
      pageIndex++;
      const currentPage = pageIndex;

      return pageData
        .getTextContent({
          normalizeWhitespace: false,
          disableCombineTextItems: false,
        })
        .then((textContent) => {
          let lastY: number | undefined;
          let text = "";
          for (const item of textContent.items) {
            if (lastY === item.transform[5] || lastY === undefined) {
              text += item.str;
            } else {
              text += "\n" + item.str;
            }
            lastY = item.transform[5];
          }

          const trimmed = text.trim();
          if (trimmed) {
            collectedPages.push({
              pageNumber: currentPage,
              text: trimmed,
            });
          }

          return text;
        });
    };

    const data = await pdf(buffer, { pagerender });
    const fullText = collectedPages.map((p) => p.text).join("\n\n");

    return {
      text: fullText,
      pages:
        collectedPages.length > 0
          ? collectedPages
          : [{ pageNumber: 1, text: data.text?.trim() ?? "" }],
    };
  } catch (error) {
    console.error("PDF Parsing Error:", error);
    throw error;
  }
}

/**
 * Word (.docx) Parsing
 */
async function parseDocx(buffer: Buffer): Promise<string> {
  try {
    const htmlResult = await mammoth.convertToHtml({ buffer });
    const html = htmlResult.value.trim();
    if (html) return htmlToStructuredText(html);
  } catch {}
  const textResult = await mammoth.extractRawText({ buffer });
  return textResult.value.trim();
}

/**
 * HTML to Structured Text
 */
function htmlToStructuredText(html: string): string {
  let text = html;
  text = text.replace(/<h1[^>]*>(.*?)<\/h1>/gi, "\n# $1\n");
  text = text.replace(/<h2[^>]*>(.*?)<\/h2>/gi, "\n## $1\n");
  text = text.replace(/<h3[^>]*>(.*?)<\/h3>/gi, "\n### $1\n");
  text = text.replace(/<h4[^>]*>(.*?)<\/h4>/gi, "\n#### $1\n");
  text = text.replace(/<h5[^>]*>(.*?)<\/h5>/gi, "\n##### $1\n");
  text = text.replace(/<h6[^>]*>(.*?)<\/h6>/gi, "\n###### $1\n");
  text = text.replace(/<p[^>]*>(.*?)<\/p>/gi, "$1\n");
  text = text.replace(/<li[^>]*>(.*?)<\/li>/gi, "• $1\n");
  text = text.replace(/<tr[^>]*>(.*?)<\/tr>/gi, "$1\n");
  text = text.replace(/<t[dh][^>]*>(.*?)<\/t[dh]>/gi, "$1\t");
  text = text.replace(/<br\s*\/?>/gi, "\n");
  text = text.replace(/<strong[^>]*>(.*?)<\/strong>/gi, "$1");
  text = text.replace(/<em[^>]*>(.*?)<\/em>/gi, "$1");
  text = text.replace(/<[^>]+>/g, "");
  text = text.replace(/&amp;/g, "&");
  text = text.replace(/&lt;/g, "<");
  text = text.replace(/&gt;/g, ">");
  text = text.replace(/&quot;/g, '"');
  text = text.replace(/&#39;/g, "'");
  text = text.replace(/&nbsp;/g, " ");
  text = text.replace(/\n{3,}/g, "\n\n");
  return text.trim();
}

/**
 * PowerPoint (.pptx) Parsing
 */
async function parsePptx(buffer: Buffer): Promise<string> {
  const ast = await officeparser.parseOffice(buffer);
  return ast.toText().trim();
}

/**
 * Excel (.xlsx) Parsing
 */
async function parseXlsx(buffer: Buffer): Promise<string> {
  const workbook = XLSX.read(buffer, {
    type: "buffer",
    cellDates: true,
    cellNF: true,
  });
  const parts: string[] = [];
  for (const sheetName of workbook.SheetNames) {
    const sheet = workbook.Sheets[sheetName];
    if (!sheet) continue;
    const csv = XLSX.utils.sheet_to_csv(sheet, {
      blankrows: false,
      dateNF: "YYYY-MM-DD",
    });
    if (csv.trim()) parts.push(`【${sheetName}】\n${csv.trim()}`);
  }
  if (parts.length === 0) throw new Error("Excel 檔案中無可讀取的資料");
  return parts.join("\n\n");
}

export const MAX_FILE_SIZE = 50 * 1024 * 1024;
export const ACCEPTED_EXTENSIONS = ".pdf,.docx,.pptx,.xlsx,.xls,.txt,.md";
export const ACCEPTED_MIME_TYPES = Object.keys(MIME_TO_TYPE);

/** Marker 支援的檔案類型 */
const MARKER_SUPPORTED_TYPES: ReadonlySet<SupportedFileType> = new Set([
  "pdf",
  "docx",
  "pptx",
  "xlsx",
]);

/**
 * 嘗試用 Marker 微服務解析，失敗自動降級回 builtin parseFile()。
 *
 * @returns ParsedDocument — 含 markerChunks 和 parsedBy 欄位
 */
export async function parseFileWithMarker(
  buffer: Buffer,
  fileType: SupportedFileType,
  fileName: string,
): Promise<ParsedDocument> {
  // 非 Marker 支援類型 → 直接走 builtin
  if (!MARKER_SUPPORTED_TYPES.has(fileType)) {
    const result = await parseFile(buffer, fileType);
    return { ...result, parsedBy: "builtin" };
  }

  const { isMarkerAvailable, parseWithMarker } =
    await import("./marker-client");

  const available = await isMarkerAvailable();
  if (!available) {
    console.info("[parseFileWithMarker] Marker 不可用，降級至 builtin");
    const result = await parseFile(buffer, fileType);
    return { ...result, parsedBy: "builtin" };
  }

  const markerResult = await parseWithMarker(buffer, fileName);
  if (!markerResult.success) {
    console.warn(
      "[parseFileWithMarker] Marker 解析失敗，降級至 builtin:",
      markerResult.error,
    );
    const result = await parseFile(buffer, fileType);
    return { ...result, parsedBy: "builtin" };
  }

  // Marker 成功但文字為空 → 圖片型 PDF，嘗試 Gemini Vision OCR
  if (!markerResult.markdown.trim()) {
    if (markerResult.page_images && markerResult.page_images.length > 0) {
      console.info(
        `[parseFileWithMarker] 圖片型 PDF，啟動 Gemini Vision OCR（${markerResult.page_images.length} 頁）`,
      );
      try {
        const { ocrPdfPages } = await import("../ai/vision-ocr");
        const ocrText = await ocrPdfPages(markerResult.page_images);
        if (ocrText.trim()) {
          return {
            text: ocrText,
            pages: [{ pageNumber: 1, text: ocrText }],
            parsedBy: "marker",
          };
        }
      } catch (ocrError) {
        console.warn("[parseFileWithMarker] Gemini OCR 失敗:", ocrError);
      }
    }
    // OCR 也失敗 → 降級至 builtin
    console.warn("[parseFileWithMarker] Marker 回傳空文字，降級至 builtin");
    const result = await parseFile(buffer, fileType);
    return { ...result, parsedBy: "builtin" };
  }

  // Marker 成功 → 建構 ParsedDocument
  return {
    text: markerResult.markdown,
    pages: [{ pageNumber: 1, text: markerResult.markdown }],
    markerChunks: markerResult.chunks,
    parsedBy: "marker",
  };
}
